### ISSUE TITLE
Non-optimal edge routing

### ISSUE THREAD

**Issue by BjBe82** [eclipse/elk#766] opened 2021-07-09 09:22 UTC
Is there a way to avoid the "non-optimal" edge routing as shown below?

![grafik](https://user-images.githubusercontent.com/61700870/122887787-84d7c400-d341-11eb-9906-9a4100bf67a0.png)

or

![grafik](https://user-images.githubusercontent.com/61700870/122887979-afc21800-d341-11eb-9d74-920f2f049b4e.png)

Example Data for https://rtsys.informatik.uni-kiel.de/elklive/json.html to reproduce this:

[ELK JSON.zip](https://github.com/kieler/elkjs/files/6692448/ELK.JSON.zip)

**Comment by soerendomroes** [comment] 2021-07-12 08:22
As far as I can see this happens because the nodes on the right are being sorted by the `semiInteractive` layout by their parent. You obviously cannot disable that since you want to maintain your node order.

For what are you using the semiInteractive layout? Are you using it to maintain your node order (but not your edge order)? If you are interested in that I could add a crossing minimization strategy that does not actually minimize the crossings but just maintains the node order as it was in the model file (e.g. your son file).

Can you confirm that your model is essentially this [graph.zip](https://github.com/eclipse/elk/files/6799739/graph.zip)? I am trying to reproduce your problem and in this abstraction from your model I only see one problem.

**Comment by uruuru** [comment] 2021-07-13 18:18
Actually, there are different reasons, I believe:
* The leftmost circle is due to the placement of long edge dummy nodes to the right, which are placed as close as possible (according to nodeEdge spacing) to the regular node above. 
* The middle circle is due to the position of dummy ports on the border of the hierarchical node. The dummy ports are introduced internally and the interior of the hierarchical node is laid out and _fixed_ prior to the edges on the outside being routed. 
* The two rightmost circles are due to an unfortunate positioning of external port dummies, which are introduced during internal processing of the hierarchy-crossing edges. You can "check" by assigning different values of `nodePlacement.strategy`.

Unfortunately it's inherent to inner workings of the layout approach.

**Comment by BjBe82** [comment] 2021-07-14 10:16
Thanks for the response so far. 
@soerendomroes We ordered the nodes alphabetically and use "elk.position" to reflect that order [1,0]...[n,0] and this only works if "semiInteractive" is enabled. For testing i just turned it off, but the edge routing is still the same. So, i think @uruuru is right that this is not related to "semiInteractive".
For example, this is with no “semiInteractive” and a littel bit different view on the data:
[42UPort-filter-view.zip](https://github.com/eclipse/elk/files/6815186/42UPort-filter-view.zip)
![grafik](https://user-images.githubusercontent.com/61700870/125602488-dbd808dc-bda7-4129-a13a-5bbb2af48fe2.png)

As you can see in the picture even without "semiInteractive" the edges are sometimes not nicely routed. 

@uruuru  What I don’t understand is that edges which should have the same routing behavior are routed nicely in 2 of the 3 cases where they point to the same element and the third one is “bad”. Based on what i understood form your comment above we have usecase 3 here with some dummy ports added for hierarchy-crossing edges. I added red ports where i think the dummy ports should be which should look like this:

![grafik](https://user-images.githubusercontent.com/61700870/125604587-1bb51426-4f66-4544-b5ca-3ac3b4e04394.png)

But i still dont get why there are additional bendingpoints on the third edge.

**Comment by uruuru** [comment] 2021-07-14 20:57
Tbh, I wasn't completely happy with my third assumption either. 

I looked at the model for your last screenshot, and there isn't anything in-between `Block_0` and `Block_108`. Hence no dummy nodes should be created there during layout. That would imply that the superfluous kink is actually due to the orthogonal edge routing between pairs of layers. Unless the handling of the cross-hierarchy edges introduces something that I'm not aware of. 

Anyway, if it were the edge routing itself my first guess would be a regression due to #653. The PR introduced a mechanism that introduces these kinds of kinks to avoid ambiguity in some cases. That is assuming that they are actually necessary ...

**Comment by BjBe82** [comment] 2021-07-26 10:10
Yes, looks like there is a regression in 0.7.0. This can clearly observed also here:

[long and short edges.zip](https://github.com/eclipse/elk/files/6877336/long.and.short.edges.zip)

Regression in 0.7.0 marked in red

![grafik](https://user-images.githubusercontent.com/61700870/126972150-d2e79444-86b2-4379-992e-2269d923bb78.png)

Other edge routings which look strange marked in blue and are present in both versions.

**Comment by uruuru** [comment] 2021-08-30 08:22
@le-cds, @soerendomroes any idea at which point this issue could've been introduced?

**Comment by BjBe82** [comment] 2022-02-09 18:15
Are there any new insights on the topic?

**Comment by soerendomroes** [comment] 2022-02-10 06:57
Currently not, however, we are planning a release and I will have a look at this at the end of February and in March.
I remember a student thesis that involved introducing more than one bend per edge. I guess that is the problem here and I will try to solve it.

**Comment by soerendomroes** [comment] 2022-03-01 10:06
Have you tried to specify a `edgeEdge`, `edgeNode`, and `portPort` spacing? The improved introduced in #653 should only activate if the spacing cannot be respected. This could also hint to a off-by-one bug or something similar.

**Comment by soerendomroes** [comment] 2022-03-03 11:22
I cannot reproduce this issue on the current master. Does anyone have an idea what might have fixed this?

**Comment by soerendomroes** [comment] 2022-03-03 11:56
This is already fixed in the` 0.7.1 `

**Comment by BjBe82** [comment] 2022-03-04 15:37
I think "this" issue is not the whole picture, we observerd during a discussion a regression which is fixed in 0.7.1 indeed 
https://github.com/eclipse/elk/issues/766#issuecomment-886564840 -> red problem. Nevertheless i can still observe many edges wich are routed in a strange way. One example are the edges marked in blue in the comment (https://github.com/eclipse/elk/issues/766#issuecomment-886564840) and there are more (currently discussing if i am allowed to share the things).

I also started to test the spacings with "edgeEdge" spacing staring from 1 to 20 while 20 increaes the obstacesl of long hierachy edges (i will provide an example if i have verified that i am allowed to share it).

**Comment by soerendomroes** [comment] 2022-03-14 07:52
I will again document what I found out about the blue problem:
spacing.portsSurrounding somehow sets the port surrounding spacing for the node itself and all its children. If I look at the [documentation](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-spacing-portsSurrounding.html) it should only apply to its children since the target is "parents"?!

We would expect that the ports of Block_78 do align with the ports of block_0 since the port spacing is always 10. However, that is not the case. The ports of block_0 have a spacing of 11 instead of 10, which seems to cause the issue.

**Comment by soerendomroes** [comment] 2022-03-14 08:08
After writing this, I am unsure whether the spacing is 9 and 10 or 10 and 11. I guess 9 and 10 is correct. In my understanding, the spacing should refer to the space between the elements (which would mean 9 and 10) and not the coordinate difference (in this case it would be 10 and 11). Maybe that is the same error that is done here.

**Comment by soerendomroes** [comment] 2022-03-14 08:15
Somehow, Block_78 is not high enough to accommodate for all ports/edges. However, this problem does not occur for Block_58.

**Comment by soerendomroes** [comment] 2022-03-14 12:25
See minimal examples with [hierarchy](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUIWDgEoQCucMAdmOgPLkAqAEkwOJMByAggBkiCGHmBQAxgiztgdAiHqM0ASV4BhQQFUAIgFEA+hvarBu8vt5EidCARxpqcPL3s4AjGgDeRNGjsHAK9ffzCMbGc0AG00AGcYAC8cdAA2AFYAOgBOVIAOAHZ0gBo0D3S0AF0-cID3AGUknEzJCDo4uChgejg49AAiaIAFFlZ60t4mA0NBfgAhfUFxtABZdVUV7RXDetUALX1K-pqAXyIzm0DHZ1d3ACYfGquAh9DazCwo2ITktKzcwolMoVaq1OoORrJFptDpdHp9NCDEZsZaTaazBZLUprXgbLY7faHY7+M7+c42UjXGi3BweTJ0LwAWgAfE5qVA3A47vS7iQCGQ2S4Oe46Qy0CzBTScNy6HcgA) (spacing is both coordinate difference and space between) and [without hierarchy](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=FAQwNg5g9gTglgFwBYFsBcACMICeBTGPAE2GIjwCUoBXBOAOwkwHkKAVACWYHFmA5AIIAZYEjgEQMAMZIcHEPSJgGTDAEk+AYSEBVACIBRAPqaOaoXooG+wYPShE8GegEYMAb2AZvWXDQQYANoYAM5wAF54mABsAKwAdACc0QAcAOyxADQYLrEYALpePvaOAMoRePFSUPQhCDAgDAghmABEgQAKrGyl2XzMhkZCAgBCBkK9GACyGmpTOlNGpWoAWgb5rcAAvrZ2Dk70AEweRd7YOP5BoRUxCcnpWTl5hT7O++WRVTV1DU0tGO0uuxJv1BsMxhNsjM+HMFktVutNjtSERyM43ABaAB8zkOKLRrgw2NxQA) (port-port spacing is coordinate difference)

**Comment by soerendomroes** [comment] 2022-03-14 12:33
Different spacings and how they work:

- [ ] comment comment
- [ ] comment node
- [ ] edge edge
- [ ] edge label
- [ ] edge node
- [ ] label label
- [ ] label node
- [ ] label port
- [ ] node node (space between)
- [ ] node self loop
- [ ] port port
- [ ] individual spacing
- [ ] additional port space

Space between means the space between the two elements is bigger than the spacing.
Coordinate difference means that the start point of e.g. edges has a minimal difference of spacing pixel.

**Closed** 2022-03-21 08:04 UTC
Labels: bug, alg-layered

**Comment by BjBe82** [comment] 2022-03-21 09:29
Sorry for the delay but i still wait for the confirmation that i am allowed to share the anatomized json data :/. In the meantime, i am allowed to show the animated images...

Tested with 0.7.1

So far i can confirm that the regression is fixed and using `'edge.thickness': '0'` removes some obstacles on the edges.

There are still things left but i am not sure now since i am still waiting for the example data. Do we keep this ticket alive or should i just create a new one?

1) Observation:
'elk.layered.crossingMinimization.semiInteractive': 'true'
with position 'elk.position' to enforce a node order

![semiInteractive_true](https://user-images.githubusercontent.com/61700870/159232926-9831f7d6-8b09-452c-9bd0-50143f7f8452.png)

vs 'semiInteractive': 'false'

![semiInteractive_false](https://user-images.githubusercontent.com/61700870/159232975-bcfe875f-93a7-414f-a271-1450c079efc6.png)

2) Observation: A more detailed diagram with 'semiInteractive': 'false' and no position (to eliminate observation 1)

![grafik](https://user-images.githubusercontent.com/61700870/159233507-00725051-e7b4-4144-a08e-16d5d9463aa3.png)

* looks like the edges are grouped by "target" hierarchy node/subnode (left of Node22)
* virtual proxy ports respect the port spacing while they could even be distributed better? (left to node 51)
* not sure what happened with the edge marked in red

**Comment by Qix-** [comment] 2022-03-21 10:41
Thanks for the continued effort on this :) Happy to see this get fixed!
