### ISSUE TITLE
Offer optional graph validation

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#246] opened 2017-09-13 21:01 UTC
Currently the layout might break at any point if the input graph is not valid.
It would be nice to have a validator for graphs. For performance reasons this probably shouldn't be running on every graph all the time. Instead the validator should probably be enabled in debug mode and also be made available for manual invocation.

If the layouters have special requirements they could offer their own validation methods that could automatically be applied on the relevant parts.

**Comment by le-cds** [comment] 2017-09-13 21:23
This has aspects of #15 that we should keep in mind if we implement this.

**Comment by spoenemann** [comment] 2017-09-14 06:46
Graph validation could be implemented with the same API as the layout option validation.

**Comment by spoenemann** [comment] 2018-01-31 14:43
> For performance reasons this probably shouldn't be running on every graph all the time.

It should be fine to always run validations that run in linear time.

**Comment by le-cds** [comment] 2018-02-23 21:47
I think eNBeWe's point about layout algorithms offering their own validation methods is important. The new sequence diagram layout algorithm, for example, has very specific requirements regarding element properties that it could validate before it is executed. We could extend the meta data language to allow algorithms to specify a validator class that the graph layout engine can call prior to invoking the layout algorithm itself.

Whether or not it should always do so is another matter. We _could_ distinguish between different validation "intensities". Linear-time validation could always be run, while more computation-intense validation could be run only if the system is in some sort of "developer mode", to help clients identify issues in their glue code.

**Comment by spoenemann** [comment] 2018-03-07 10:02
The problem is that currently the layout algorithms to be applied are resolved in the RecursiveGraphLayoutEngine, so that information is not available yet when the graph is validated. However, we could implement my proposal from https://github.com/eclipse/elk/issues/104#issuecomment-293178224 in order to apply algorithm-specific validation.

**Closed** 2018-04-12 08:24 UTC
Labels: new feature
