### ISSUE TITLE
NPE when portConstraints: FIXED_POS for Edges Between Nodes

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/elk#256] opened 2017-10-05 21:02 UTC
### Test Case:
```
algorithm: layered

node N1 {
	layout [
		position: 0,0
		size: 100, 100
	]
}
	
node N2 {
	layout [
		position: 0,0
		size: 100, 100
	]
	portConstraints: FIXED_POS
}

edge N2 -> N1
```

### Exception
> java.lang.NullPointerException
> 	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.transformEdge(ElkGraphImporter.java:929)
> 	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.importFlatGraph(ElkGraphImporter.java:195)
> 	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.importGraph(ElkGraphImporter.java:111)
> 	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:34)
> 	at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:1)
> 	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:53)
> 	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183)
> 	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
> 	at org.eclipse.elk.core.debug.views.graph.LoadGraphAction.layout(LoadGraphAction.java:98)
> 	at org.eclipse.elk.core.debug.views.graph.LoadGraphAction.run(LoadGraphAction.java:81)
> 	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
> 	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
> 	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
> 	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
> 	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
> 	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
> 	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
> 	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
> 	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
> 	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
> 	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
> 	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
> 	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
> 	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
> 	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
> 	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
> 	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
> 	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
> 	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
>

**Comment by le-cds** [comment] 2017-10-06 08:30
This issue will already have been fixed in the upcoming release. However, note that setting `FIXED_POS` port constraints on a node which does not in fact have any ports will not yield good layout results in the first place.

**Comment by philip-alldredge** [comment] 2017-10-06 12:25
Thank you.

Is there an ETA for when will the fix be available in the nightly builds? The exception occurs in the current nightlys.

I had removed other elements such as ports from the graph to avoid clutter.

**Comment by uruuru** [comment] 2017-10-06 13:08
It's a different issue, where an edge section is accessed that is `null`:

```
if (sourceLNode.getProperty(LayeredOptions.PORT_CONSTRAINTS).isSideFixed()) {
    sourcePoint = new KVector(edgeSection.getStartX(), edgeSection.getStartY());
```

The code is only executed if the original edge doesn't already connect to port(s), and (if I read it correctly  ) is supposed to allow assigning a proper port type and port side.

**Comment by le-cds** [comment] 2017-10-06 13:15
Interesting that I couldn't reproduce the error. I'll take another look at this before finally pushing out the new release this weekend.

**Comment by le-cds** [comment] 2017-10-09 09:01
The NPE should be fixed.

**Closed by le-cds** 2017-10-09 09:01 UTC
Labels: bug, elk-layered

**Comment by philip-alldredge** [comment] 2017-10-10 14:40
Thanks for the quick fix.
