### ISSUE TITLE
Port Alignment Affects Edges Between Nodes

### ISSUE THREAD

**Issue by philip-alldredge** [eclipse/elk#271] opened 2017-11-28 20:59 UTC
See the following graph. When portAlignment is set to begin on N10, the edge routing behavior changes so that the edges are routed to the top left of N10. This only occurs when port alignment is set as in the model and there are multiple edges connected to N10. Removing the ports while keeping the port alignment property shows the same behavior.

Is there any way to maintain the edge routing behavior regardless of the port alignment?

```
graph G1
algorithm: org.eclipse.elk.layered
node N1 {
	node N2 {
		layout [
			position: 12, 12
			size: 587, 2070
		]
		portPort: 0.0
		
		node N3 {
			layout [
				position: 155, 638
				size: 200, 100
			]
			portAlignment.default: BEGIN
		}
		node N4 {
			layout [
				position: 375, 1118
				size: 200, 100
			]
			portAlignment.default: BEGIN
		}
		
		node N8 {
			layout [
				position: 155, 398
				size: 200, 100
			]
			portAlignment.default: BEGIN
		}
		node N9 {
			layout [
				position: 155, 1118
				size: 200, 100
			]
			portAlignment.default: BEGIN
		}
		node N10 {
			layout [
				position: 375, 415
				size: 200, 100
			]
			alignment: BOTTOM
			portAlignment.default: BEGIN // Causes unintended edge routing behavior.
			
			port P1 {
				layout [
					size: 20, 20
				]
			}
			
			port P2 {
				layout [
					size: 20, 20
				]
			}
		}		
		
		edge E1: N3 -> N10 {
			yo: true
		}
		edge E2: N8 -> N10 {
			yo: true
		}
		edge E3: N9 -> N4 {
			yo: true
		}
	}
}
```

**Comment by philip-alldredge** [comment] 2017-11-28 21:00
![example](https://user-images.githubusercontent.com/1376364/33343974-d911e958-d44c-11e7-8b86-d9327b5bd9bc.png)

**Comment by philip-alldredge** [comment] 2018-02-14 16:18
Any chance of this being fixed in an upcoming release?

**Comment by le-cds** [comment] 2018-02-20 09:38
Yes, I'm scheduling it to be fixed for 0.4.0.

**Comment by philip-alldredge** [comment] 2018-02-20 14:14
Great

**Comment by le-cds** [comment] 2018-02-27 13:49
Turns out that it's not, in fact, a bug as such. With a bit of configuration, this is the result I'm getting:

![screen shot 2018-02-27 at 14 46 13](https://user-images.githubusercontent.com/7465584/36732097-fdeeb3a6-1bcc-11e8-94c7-d0cc63db9bb9.png)

The problem is that several spacing values need to be configured for `BEGIN` to work properly:

* `CoreOptions.SPACINGS_PORT_PORT` needs to be set to a value >0 that defines how much space to leave between ports. The default port alignment, `JUSTIFIED`, calculates this automatically, which is why you only see the problem with `BEGIN`. In my example, I set this to 10.
* `CoreOptions.SPACINGS_PORTS_SURROUNDING` needs to be set to define how much space to leave between the node border and the outermost ports at any given port side. In my example, I set the space to 10 on all sides.

I'm closing the issue for now, but feel free to reopen it if you have any questions or if I missed anything.

**Closed by le-cds** 2018-02-27 13:49 UTC
Labels: bug
