### ISSUE TITLE
FIXED_SIDE port constraint has incident on edge layout

### ISSUE THREAD

**Issue by lredor** [eclipse/elk#464] opened 2019-10-28 08:38 UTC
As explained on [gitter](https://gitter.im/eclipse/elk?at=5db1b584e886fb5aa2e9e95d), I've fixed the sides of ports with "input port" to the WEST side and "output port" to the EAST side. The result corresponds to what I expect but it seems to have undesirable side effect: as if when the side of a border node is fixed, the "order" of border nodes are not the same after the result.

In my case, the result is that some edges intersect each other.

Here is an example. Sorry it is a big diagram but I not succeeded to have a minimal reproduction case. I have highlighted in red the "interesting" part.

- BigDiagram-InitialState.png : Initial state of the diagram
![BigDiagram-InitialState](https://user-images.githubusercontent.com/1825882/67663689-6059f780-f966-11e9-89c6-40fcaa83b17f.png)
- BigDiagram-ResultWithoutFixedSide.png: The result without having fixed the side of the ports: The edges with label 1, 2, 3 and 4, and their associated ports are "correctly" layouted and there is no edge intersection.
![BigDiagram-ResultWithoutFixedSide](https://user-images.githubusercontent.com/1825882/67663729-6ea81380-f966-11e9-9cd8-abac73e800a2.png)
- BigDiagram-ResultWithFixedSide.png: The result with having fixed the side of the ports: The edge with label 1 intersects all other edges.
![BigDiagram-ResultWithFixedSide](https://user-images.githubusercontent.com/1825882/67663713-66e86f00-f966-11e9-9c6d-053a06d9b286.png)

It seems to be a bug as there is no reason for edge with label 1 to not be the first outgoing from the node "My concerned source".

The corresponding elkg samples:
* [BigDiagramWithoutFixedSize.elkg.txt](https://github.com/eclipse/elk/files/3777783/BigDiagramWithoutFixedSize.elkg.txt)
* [BigDiagramWithFixedSize.elkg.txt](https://github.com/eclipse/elk/files/3777785/BigDiagramWithFixedSize.elkg.txt)

**Comment by le-cds** [comment] 2020-02-12 13:52
Such edge crossing issues are infuriating, and situations such as occur on a pretty regular basis. However, they are to be expected since crossing minimization is a very hard problem to solve optimally, especially when hierarchy-crossing edges are involved, as they are here. I dare say that the problem would not appear if the involved nodes were all part of the same hierarchy level.

Having said that, I tried – as you seem to have – to reduce your example, but at one point or another the problem always disappeared. I'm afraid that this will make investigating the cause nigh impossible. Thus, I'm afraid I'll have to close the issue. Feel free to reopen it if you have any other leads.

**Closed by le-cds** 2020-02-12 13:52 UTC
Labels: alg-layered, bug, wontfix

**Comment by lredor** [comment] 2020-02-12 17:20
OK, thanks to had a look.
