### ISSUE TITLE
force.repulsivePower does not produce bendPoints

### ISSUE THREAD

**Issue by timothypratley** [eclipse/elk#806] opened 2022-03-15 23:00 UTC
Expected: Supplying a `force.repulsivePower` in `layoutOptions` for an `edge` should result in `bendPoints` for the edge.

Actual: No `bendPoints` are produced.

The [documentation for repulsivePower](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-force-repulsivePower.html) indicates that `bendPoints` should be created, but they are not.

Example 1: Basic force graph JSON definition

```
{
  id: "root",
  layoutOptions: {
    'algorithm': 'force'
  },
  children: [
    { id: "n1", width: 30, height: 30},
    { id: "n2", width: 30, height: 30},
    { id: "n3", width: 30, height: 30}
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ], layoutOptions: {'org.eclipse.elk.force.repulsivePower': 4}},
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ], layoutOptions: {'org.eclipse.elk.force.repulsivePower': 2}},
  ]
}
```

The resulting layout contains no `bendPoints`.

[ELK Demonstrator](http://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvKBBAOQF4DmKSk6ABYBbdvHYAzPgGMApu1wBfHBGmDIeaEln14AbVwRgUOInoBGbGADuMIfADMABixhBsyN0HpHT5YbBjGHgEegAmK1toezBnV3dPb19-NkCTEPoHSLtBX3iPLx9Yv1wAXRUwWWhuWWYwA1Sg0wRZS1dGMiQ5Or0zSzBysHQCJBr0HrMIgddCEnJqWgY64HY+bgA6WWk8SCpGWU28AGt1qS6D7SpSPEZIADdZAAUUa1kkMTAAFkUUtiaQ2QRdqdbr6PoIaZDEZjCahLKQ2ZkSg0OhMFirUabba7faHE5nOTrS7XW4PZ6vd7wMI-CqlECKIA)

I observed this behavior in my JavaScript project (via ELKJS). The output layout has no `bendPoints`.

The nodes are placed further apart.

I have not tested this directly in Java native.

**Comment by timothypratley** [comment] 2022-03-15 23:04
After some experimentation it seems the correct way to specify this option is as a `layoutOption` per edge:
```
{
  id: "root",
  layoutOptions: {
    'algorithm': 'force'
  },
  children: [
    { id: "n1", width: 30, height: 30},
    { id: "n2", width: 30, height: 30},
    { id: "n3", width: 30, height: 30}
  ],
  edges: [
    { id: "e1", sources: [ "n1" ], targets: [ "n2" ], layoutOptions: {'org.eclipse.elk.force.repulsivePower': 4}},
    { id: "e2", sources: [ "n1" ], targets: [ "n3" ], layoutOptions: {'org.eclipse.elk.force.repulsivePower': 2}},
  ]
}
```
So I'm closing this issue.

**Comment by soerendomroes** [comment] 2022-03-21 08:28
I somehow got a mail that you closed this and found a way to specify it correctly. Can I close the ticket or does it still not work as intended?

**Comment by soerendomroes** [comment] 2022-03-22 07:08
Thank you Timothy.
If you can create it in the `ELK Demonstrator` it is fine. I prefer the `elkt` format over the `json` format but both work and you can [convert between the two](https://rtsys.informatik.uni-kiel.de/elklive/conversion.html) if necessary.

It is always nice to see a sketch of how you think the drawing should look like, especially if you have an issue with a layout algorithm that is not the `layered` algorithm.
In your case, I guess you expect that the longer of the two edges has a bend in it since the created bendpoints should repel each other.

**Comment by timothypratley** [comment] 2022-03-22 18:32
:+1: Here is an `elkt` version:

```

**Comment by timothypratley** [comment] 2022-03-22 19:01
:+1: 

Example 1: Two nodes, 2 edges with repulsivePower on edges [elkt demonstrator](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGAM2wGMBTFAO3gBMqZaBGGAbxQEh0wBPeAFckMANowAzjgBeVEgGYADABoYymAF0UAXzqNmtAEycefQSPFTZ89artbdKKg2DMqrEmxgBaAHwsJlzcIFQQQujSAG5UAArwAO5UICQALE4ubjBURl4m-izswaHhkTgx8UkpMOk6QA)

```
graph root
algorithm: force
node n1 {
	layout [ size: 30, 30 ]
}
node n2 {
	layout [ size: 30, 30 ]
}
edge e1: n1 -> n2 {
	repulsivePower: 4
}
edge e2: n2 -> n1 {
	repulsivePower: 4
}
```

Produces:

![repulsive](https://user-images.githubusercontent.com/49298/159555509-64c5cbc7-3566-4006-b527-f1571f179fcc.png)

There are no bend points.


Expected (my annotations in red):

![repulsive-edges](https://user-images.githubusercontent.com/49298/159555569-56d35783-1113-46be-a1fe-f29923b9ba5b.png)

There should be bend points, and "such bend points are regarded as repelling particles in the force model" indicates that they edges would be pushed apart.


Example 2: using ports [elkt demonstrator](http://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=OYJwhgDgFgBCD28AuAoMAbY8QEslQFsAuGAM2wGMBTFAO3gBMqZaBGGAbxQEh0wBPeAFckMANowAzjgBeVEgGYADABoYymAF0UMXTAjYkAYXi1JScDlpJJJAGIBJABoBRACIB9AMoO3LnXoGIKIQrMwcAHpBSAB00kwkLgCCXgAqAL4ButH6rADunFGGcTgJMADqLmmZmfRMLABMnDx8giLiUrLy6qo9Wln6hiZmFmBWNvbO7t6+-nqDwfoN4UXBJWXJ1QM5EA0FkdHr3ZVbmVQMwMxUrCRsMaHMALQAfI33y83cIFQQQujSADcqAAFeB5KggEgAFhQZwuVwatwa7wKLxYrHu+U+31+-xwQNB4MhMBh6SAA)

```
graph root
algorithm: force
node n1 {
	layout [ size: 30, 30 ]
    portConstraints: FIXED_SIDE
    port p1e {^port.side: EAST}
    port p1w {^port.side: WEST}
}
node n2 {
	layout [ size: 30, 30 ]
    portConstraints: FIXED_SIDE
    port p2e {^port.side: EAST}
    port p2w {^port.side: WEST}
}
edge e1: n1.p1e -> n2.p2e {
	repulsivePower: 4
}
edge e2: n2.p2w -> n1.p1w {
	repulsivePower: 4
}
```
This just seems... odd! :)

**Comment by timothypratley** [comment] 2022-03-23 07:53
Related; setting the `model` to `EADES` pushes the nodes a very very long distance apart with `repulsivePower` at 1 or more :man_shrugging:

**Closed** 2023-03-09 14:12 UTC
