### ISSUE TITLE
ModelOrderPortComparator seem to not fulfil the comparator contract

### ISSUE THREAD

**Issue by dhuebner** [eclipse/elk#918] opened 2023-04-06 11:08 UTC
For some of our models we get this exception thrown. It looks like the `ModelOrderPortComparator` implementation is bogus.
I can't provide the test data yet, but will do so as soon as I reduced our huge model to a small reproducible example.

```
stack trace: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.Collections.sort(Collections.java:179)
	at org.eclipse.elk.alg.layered.intermediate.SortByInputModelProcessor.process(SortByInputModelProcessor.java:69)
	at org.eclipse.elk.alg.layered.intermediate.SortByInputModelProcessor.process(SortByInputModelProcessor.java:1)
	at org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:606)
	at org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:152)
	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:56)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:250)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:218)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:96)
	at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
	at io.typefox.elkserver.StdioElkServer.run(StdioElkServer.java:27)
	at io.typefox.elkserver.AbstractElkServer.start(AbstractElkServer.java:35)
	at io.typefox.elkserver.ElkServerApplication.main(ElkServerApplication.java:25)
```

I also noticed that the implementation is not that performant. The bottleneck in my case is due to many `HashSet` reads.

**Comment by dhuebner** [comment] 2023-04-06 12:27
@soerendomroes 
I hope this example file helps to reproduce. I don't know how to convert it to an `elkt` file.
[918_modelOrderportComparator.json.zip](https://github.com/eclipse/elk/files/11170591/918_modelOrderportComparator.json.zip)

**Comment by soerendomroes** [comment] 2023-04-06 13:25
You are using ELK 0.8.1 correct? The error seems to be fixed on the ELK master or it does not occur for me.

I am not converting the graph but basically doing the same thing you are doing in an IDE that recognizes the elkj extension as the ELK Json format.

**Comment by soerendomroes** [comment] 2023-04-06 13:47
Nevermind, your code snippet reproduces the issue. However, I am not sure, why elklive can handles the graph without an exception.

**Comment by dhuebner** [comment] 2023-04-11 07:02
@soerendomroes 
It could depend on the JVM. Also as workaround one can use `-Djava.util.Arrays.useLegacyMergeSort=true` to use Legacy sort. Legacy sort doesn't throw an Exception but is much slower for large arrays.

**Closed** 2023-06-27 11:02 UTC
Labels: alg-layered
