### ISSUE TITLE
Adjacent hyperedges are not merged for hyperedges with multiple sources and targets

### ISSUE THREAD

**Issue by eNBeWe** [eclipse/elk#234] opened 2017-09-06 08:40 UTC
In the attached example the two hyperedge segments should probably be merged.
```
feedbackEdges:true
elk.direction: RIGHT
randomSeed: 4

node N1 {
	port O
}
node N2 {
	port I
	port O
}
node N3 {
	port I
	port O
}
node N4 {
	layering.layerConstraint: LAST
	port I
}

edge N2.O -> N3.I

edge N3.O -> N4.I
edge N3.O -> N2.I

edge N1.O -> N4.I
edge N1.O -> N2.I
```
![hyperedge](https://user-images.githubusercontent.com/3796429/30102374-bc1d491c-92ef-11e7-9d75-35520039f0a2.png)

**Comment by eNBeWe** [comment] 2017-09-06 09:07
Initial investigation:
One horizontal segment is the edge from N1 to N4, the other is the edge from N3 to N2. For this reason, the DummyMerger doesn't allow these to be merged.

**Comment by le-cds** [comment] 2018-04-27 09:38
#308 is a duplicate of this, but #308 was referenced in commits, so...

**Closed by le-cds** 2018-04-27 09:38 UTC
Labels: duplicate, elk-layered
