### ISSUE TITLE
Layered algorithm produces overlapping parallel edge segments for graphs with crossover fixed-position ports

### ISSUE THREAD

**Issue by arotenberg** [eclipse/elk#318] opened 2018-03-29 17:41 UTC
[Example 1](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE4AKmAxjkjiXAHQDOcUwcOYW6AygEkAspQAyAUSLSyFNCQCMaAN5E06jNggBXOGgDaaVjABeOdACYADABo01tAF01GgA7Q4AYQgl2nGEys6ABiggAaEgAiAPqUAPL8LuruUHquSqoaWZpYOnqG7sZwMD6WtmgALEam5pV2Vc5ZAL5JaClpFiqtWZi5ugZtEEUlJGV2Cp3GZugV9U6tLS2yOPKdmRq9eQNTtdZ2Do1uHt6+HMABcEFooREx8YlZ7W0Z3Rta-QVD8CPoALSzlWq0zqgMO6hajw8bTWr3Umw+g2GpTQ-3GkxqMzmYLQiyIhDAK0UzHSKIAfKtiZ08QQCfIFJSyRT0kA) (requires `nodePlacement.strategy: SIMPLE`)

[Example 2](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUEQHYQE5qkCMaA3kWsxthAK5xoDaaAzjABeOdACYADABo0ogBxoAukxYAHaHADCEUnzhRgMUnD7oAYgEkAGgFEAIgH0ACgHkAysuZqoXFXUYsA1iwOLl41ATgYbTEpNAAWfiEReOkEpQCAXw80Lx9RBmyAzGDOHhyICKjSGOkafIFhdDjUxWysgNycgGYCwJZikLLw+CqamXFExpT41syiLPJKanz-frZS3gbkiWk5WdV1LR09AyMTNAsbBxd3DvUcv0K1ktDyyui0AFpmma2mlvSLHaB28ORWT2YAw2bxGH2+tXqSX+M0BzGBnnuKh6qz6UNew0icJ+EkmyR+aTa8yIhDAVFoADpfF8AHzLRn5akEWnUGjslls3yc7kMrH80iiRldIA) (does not use `nodePlacement.strategy: SIMPLE`)

This came up in [Gitter discussion](https://gitter.im/eclipse/elk?at=5abbb11a35dd17022eacdc19) about whether ELK Layered will always produce layouts that are free of such overlaps.

The underlying issue is that the Layered algorithm can currently place at most one vertical edge segment per edge between each adjacent pair of node layers. However, any non-overlapping orthogonal layout for the linked graphs requires one of the edges to have multiple vertical segments.

I'm not sure, but I think it may be possible to contrive a family of two-layer graphs with _n_ fixed-position ports in which any orthogonal layout must have some edge with Ω(_n_) vertical segments between the two layers.

**Comment by arotenberg** [comment] 2018-03-29 17:55
Hmm... Actually, every pair of layers can be drawn with at most 2 vertical segments per edge: you just route all of the edges from the first layer out of the way in a big bundle, then route them one at a time to the appropriate locations in the second layer in sequence. This requires Ω(_n_) vertical segments—as well as Ω(_n_) additional vertical and horizontal space—but only uses 2 vertical segments _per edge_. So in principle you should never need more than those 2 S-bends per edge, it's just a question of how to make it look good.

**Comment by Nic30** [comment] 2018-04-15 12:03
I also suffer from this issue.

**Comment by uruuru** [comment] 2018-04-16 09:13
> Could be a nice research topic :-)

I agree.

**Comment by thiesaweber** [comment] 2018-11-16 09:54
So here am I - rescuing the day with my bachelor thesis.

@arotenberg @Nic30 
Right now I am looking for some bigger "real application" examples and would really appreciate it if you could offer me any.
Of course there are many examples of triggering this issue by fixed port positions or hierarchical parenting on purpose, but I'm really interested in nonforced occurences to reference and use it in my work.

**Comment by Nic30** [comment] 2018-11-16 20:34
@thiesaweber I can generate you very large graphs from real hardware. But how large you want? I mean that there is about 10K nodes in just a simple CPU. I am using this library to generate [interactive documentation](https://hwtlib.readthedocs.io/en/latest/) the graph is json and the path you can see in url https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.clocking.clkDivider.ClkDiv3-0.json

(Also click on component to see what is inside.)

I am not sure how intuitive it is to open the schematic and if you can find it in my doc. but that is the experimet you agreed with :)

**Comment by thiesaweber** [comment] 2018-11-17 08:31
@Nic30 
Thanks for the quick reply. 
I guess "large" was a bit inaccurate, sorry.  
I'm looking for any real example of a graph, that suffers from this issue. Such an examples doesn't have to be very big. In fact your example has a good size to bind it in a thesis, but right now I'm not seeing any occurences of overlappings in it.

**Comment by Nic30** [comment] 2018-11-17 10:45
@thiesaweber Problem is that I do not remember which schematics are suffering from this issue.
But I think that this is not a problem because this issue is caused by "X" shape in connections between two edges. I mean it can be added to any graph and you probably do not need any complex graph to create fix for this issue.

**Comment by thiesaweber** [comment] 2018-11-17 11:31
@Nic30 
In fact this issue is bounded to a number of limitations. 

As you can see in this topic's initial examples:
> Example 1 (requires nodePlacement.strategy: SIMPLE)
Example 2 (does not use nodePlacement.strategy: SIMPLE)

For 1 we need a whole other node placement strategy many users don't use anyway. And for both examples you need fixed port positions (fixed port order plus fixed port sides works as well), which one has to define explicitly, too.
There are other cases with other restrictions, for example between two hierarchical parent nodes.
You are right, it's just this "X" shape, but producing and not forcing it on purpose seems to be not that easy.

My point is now to find out the relevance of this issue and justify it as whole topic for my work. 
Sure, I could build me my own, but a real life example would be much more meaningful.

**Closed** 2020-07-10 13:45 UTC
Labels: alg-layered, enhancement, thesis
