### ISSUE TITLE
Edges overlapping due to bigger spacing

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#64] opened 2016-07-17 09:53 UTC
Increasing the spacing may result in edges overlapping. In the following example, the edges `g7b` to `g8`, `_condg7` to `g6` and `g3` to `g4`, `_condg3` to `g2` overlap

![guardscgspacing](https://cloud.githubusercontent.com/assets/7465584/16899935/ddc9048e-4c14-11e6-9511-8d3bf872e26f.png)

[Files to reproduce](https://github.com/eclipse/elk/files/367763/Archive.zip)

_This used to be KIELER ticket [KIPRA-1798](https://rtsys.informatik.uni-kiel.de/jira/browse/KIPRA-1798)._

**Comment by uruuru** [comment] 2016-12-20 09:36
Do you have a suggestion to solve this?

**Comment by le-cds** [comment] 2016-12-20 10:18
No, I haven't looked at the issue in detail yet.

**Comment by spoenemann** [comment] 2018-04-27 09:39
Yes, I'd say this is a duplicate of #318.

**Closed** 2019-08-06 19:35 UTC
Labels: alg-layered, bug, duplicate
