### ISSUE TITLE
Invalid unsupported option warning in elkt

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#184] opened 2017-06-27 11:44 UTC
The following elkt file raises the following warning, but the relevant layouter (`layered`) supports the `edgeLabels.placement` option.

```
The algorithm 'org.eclipse.elk.box' does not support the option
'org.eclipse.elk.edgeLabels.placement'.
```

```
node BarcodeReader {
	algorithm: org.eclipse.elk.box
	node N1 {
		algorithm: layered
		node Waiting {
			layout [ size: 72, 34 ]
		}
		node Driving_ {
			layout [ size: 73, 34 ]
		}
		edge Driving0: Waiting -> Driving_ {
			label L2: "drive / leftSpeed = speed; rightSpeed = speed" {
				layout [ size: 328, 17 ]
				edgeLabels.placement: CENTER
			}
		}
	}
}
```

**Comment by spoenemann** [comment] 2017-07-20 14:46
Duplicate of #164

**Closed** 2017-07-20 14:46 UTC
Labels: bug
