### ISSUE TITLE
NPE on BetweenLayerEdgeTwoNodeCrossingsCounter

### ISSUE THREAD

**Issue by ignaciospain1** [eclipse/elk#458] opened 2019-09-25 09:32 UTC
Hello,

we are getting an exception when executing  `RecursiveGraphLayoutEngine.layout(...)` which to our eyes seem to produce a correct layout anyways. Code:

```
 RecursiveGraphLayoutEngine engine = new RecursiveGraphLayoutEngine();
 engine.layout(rootNode, new BasicProgressMonitor());
```

which produces:

    
```
      Message: null
      Cause  : null

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.addAdjacencyOf(BetweenLayerEdgeTwoNodeCrossingsCounter.java:279) 

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.iterateTroughEdgesCollectingAdjacencies(BetweenLayerEdgeTwoNodeCrossingsCounter.java:261)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.getAdjacenciesSortedByPosition(BetweenLayerEdgeTwoNodeCrossingsCounter.java:250)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter$AdjacencyList.<init>(BetweenLayerEdgeTwoNodeCrossingsCounter.java:246)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter.getAdjacencyFor(BetweenLayerEdgeTwoNodeCrossingsCounter.java:168)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter.addEasternCrossings(BetweenLayerEdgeTwoNodeCrossingsCounter.java:151)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.BetweenLayerEdgeTwoNodeCrossingsCounter.countBothSideCrossings(BetweenLayerEdgeTwoNodeCrossingsCounter.java:142)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.CrossingMatrixFiller.fillCrossingMatrix(CrossingMatrixFiller.java:68)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.CrossingMatrixFiller.getCrossingMatrixEntry(CrossingMatrixFiller.java:51)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.SwitchDecider.doesSwitchReduceCrossings(SwitchDecider.java:136)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.switchIfImproves(GreedySwitchHeuristic.java:116)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.sweepDownwardInLayer(GreedySwitchHeuristic.java:108)      

org.eclipse.elk.alg.layered.intermediate.greedyswitch.GreedySwitchHeuristic.setFirstLayerOrder(GreedySwitchHeuristic.java:75)      

org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossingsNoCounter(LayerSweepCrossingMinimizer.java:167)      

org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.minimizeCrossings(LayerSweepCrossingMinimizer.java:143)      

org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:121)      

org.eclipse.elk.alg.layered.p3order.LayerSweepCrossingMinimizer.process(LayerSweepCrossingMinimizer.java:1)

org.eclipse.elk.alg.layered.ElkLayered.layout(ElkLayered.java:592)

org.eclipse.elk.alg.layered.ElkLayered.doLayout(ElkLayered.java:152)

org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:57)  

org.eclipse.elk.core.RecursiveGraphLayoutEngine.executeAlgorithm(RecursiveGraphLayoutEngine.java:248)    

org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:216)

org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:94)

org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:72)
```

**Comment by le-cds** [comment] 2019-09-30 08:37
In order to be able to take a look at this, we need two more things:

1. The actual exception (you provided the stack trace, but not the actual exception)
1. A graph that reproduces the issue.

**Comment by ignaciospain1** [comment] 2019-09-30 10:41
Well, unfortunately lack of access and corporate rules might make this difficult for both of us. I think this might not be of a lot of help but lets try:

1. That´s the only information coming to logs I have access to. Message null cause null etc...
2. This is one of the affected graphs (Which I was forced to redact names out from):

![Graphic-Initial](https://user-images.githubusercontent.com/10697421/65871711-3f11e580-e37f-11e9-9f85-e2a6a400e225.png)

The problem comes when adding to it the object aaa and layout:

![Graphic](https://user-images.githubusercontent.com/10697421/65871689-33262380-e37f-11e9-8367-c7b88265831a.png)

**Comment by le-cds** [comment] 2020-02-07 14:58
I'm afraid this is not enough for me to try and reproduce the issue. However, we do have quite extensive debugging and logging features since release 0.6.0. [This page](https://www.eclipse.org/elk/documentation/algorithmdevelopers/algorithmdebugging.html) describes those features.

Here's what you need to do:
* Open the preferences and enable _Generate debug information_ and _Store debug information_. This will cause ELK to persist debug data of all the layout runs.
* Open the _Layout Graph_ view and execute layout on your diagram twice: once on the unproblematic case, and once on the problematic case.
* Right-click the corresponding layout runs in the _Layout Graph_ view and select _Reveal Log Folder_.
* The files I'll be needing are `input.elkg` and `result.elkg`. They will likely contain the strings in your labels, which you will want to redact. That won't be a problem, since they are not of interest to this issue.

Sending me those files will hopefully allow me to reproduce the issue.

**Comment by le-cds** [comment] 2020-03-25 13:31
I'll close this for now. Feel free to reopen the issue once you have further input. 🙂

**Comment by uruuru** [comment] 2020-03-29 09:14
@ignaciospain1 note that a workaround could be to turn of [greedy switch](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingminimization-greedyswitch-type.html), i.e. set it to `OFF`. The results, in terms of layout quality, shouldn't suffer too much. 

@le-cds I presume you simply forgot to execute your plan to close the issue. I'll do so for you.

**Closed by uruuru** 2020-03-29 09:14 UTC
Labels: question

**Comment by le-cds** [comment] 2020-03-31 10:19
@uruuru Indeed. Thanks. 😄
